version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn jacoco:report
      - store_artifacts:
          path:  target
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)